apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-govb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-govb@sha256:085154eec38bb0b91f4d2eb5d3c5868f1e89c5281f24994397794f90d82a44fb
        name: my-nodejs
        resources: {}
status: {}
